# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adsimdetector/releases/download/2024.6.1/ibek.ioc.schema.json

ioc_name: "{{ _global.get_env('IOC_NAME') }}"
description: Example simulated camera for AXIS

entities:
  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: ADSimDetector.simDetector
    PORT: AXIS1
    P: "XF:23ID1-ES{AXIS}"
    R: "cam1:"
    # DATATYPE:0 = Int8 - TODO add an enum to the support yaml
    DATATYPE: 0
    WIDTH: 1024
    HEIGHT: 1024

  - type: epics.PostStartupCommand
    command: |
      dbpf XF:23ID1-ES{AXIS}cam1:AcquireTime 0.1
      dbpf XF:23ID1-ES{AXIS}image1:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}Proc1:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}Proc2:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}Trans1:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}Trans2:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}Over1:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}ROI1:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}ROI2:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}ROI3:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}ROI4:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}Stats1:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}Stats2:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}Stats3:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}Stats4:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}Stats5:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}PVA1:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}HDF1:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}TIFF1:EnableCallbacks 1
      dbpf XF:23ID1-ES{AXIS}cam1:SimMode Peaks
      dbpf XF:23ID1-ES{AXIS}cam1:PeakStartX 450
      dbpf XF:23ID1-ES{AXIS}cam1:PeakStartY 450
      dbpf XF:23ID1-ES{AXIS}cam1:PeakNumX 50
      dbpf XF:23ID1-ES{AXIS}cam1:PeakNumY 50
      dbpf XF:23ID1-ES{AXIS}cam1:PeakStepX 2
      dbpf XF:23ID1-ES{AXIS}cam1:PeakStepY 2
      dbpf XF:23ID1-ES{AXIS}cam1:PeakWidthX 5
      dbpf XF:23ID1-ES{AXIS}cam1:PeakWidthY 5
      dbpf XF:23ID1-ES{AXIS}cam1:PeakVariation 6
      dbpf XF:23ID1-ES{AXIS}cam1:Acquire 1

  - type: ADCore.NDProcess
    PORT: PROC1
    P: "XF:23ID1-ES{AXIS}"
    R: "Proc1:"
    NDARRAY_PORT: AXIS1

  - type: ADCore.NDProcess
    PORT: PROC2
    P: "XF:23ID1-ES{AXIS}"
    R: "Proc2:"
    NDARRAY_PORT: AXIS1

  - type: ADCore.NDTransform
    PORT: TRANS1
    P: "XF:23ID1-ES{AXIS}"
    R: "Trans1:"
    NDARRAY_PORT: PROC1

  - type: ADCore.NDTransform
    PORT: TRANS2
    P: "XF:23ID1-ES{AXIS}"
    R: "Trans2:"
    NDARRAY_PORT: PROC2

  - type: ADCore.NDOverlay
    PORT: OVER1
    P: "XF:23ID1-ES{AXIS}"
    R: "Over1:"
    NDARRAY_PORT: TRANS2

  - type: ADCore.NDROI
    PORT: ROI1
    P: "XF:23ID1-ES{AXIS}"
    R: "ROI1:"
    NDARRAY_PORT: TRANS1

  - type: ADCore.NDROI
    PORT: ROI2
    P: "XF:23ID1-ES{AXIS}"
    R: "ROI2:"
    NDARRAY_PORT: TRANS1

  - type: ADCore.NDROI
    PORT: ROI3
    P: "XF:23ID1-ES{AXIS}"
    R: "ROI3:"
    NDARRAY_PORT: TRANS1

  - type: ADCore.NDROI
    PORT: ROI4
    P: "XF:23ID1-ES{AXIS}"
    R: "ROI4:"
    NDARRAY_PORT: TRANS1

  - type: ADCore.NDPvaPlugin
    PORT: PVA1
    PVNAME: XF:23ID1-ES{AXIS}PVA1:OUTPUT
    P: "XF:23ID1-ES{AXIS}"
    R: "PVA1:"
    NDARRAY_PORT: OVER1

  - type: ADCore.NDStdArrays
    PORT: image1
    P: "XF:23ID1-ES{AXIS}"
    R: "Image1:"
    NDARRAY_PORT: AXIS1
    TYPE: Int8
    NELEMENTS: 1048576
    FTVL: CHAR

  - type: ADCore.NDStats
    PORT: Stats1
    P: "XF:23ID1-ES{AXIS}"
    R: "Stats1:"
    NDARRAY_PORT: ROI1
    XSIZE: 1024
    YSIZE: 1024
    HIST_SIZE: 20

  - type: ADCore.NDStats
    PORT: Stats2
    P: "XF:23ID1-ES{AXIS}"
    R: "Stats2:"
    NDARRAY_PORT: ROI2
    XSIZE: 1024
    YSIZE: 1024
    HIST_SIZE: 20

  - type: ADCore.NDStats
    PORT: Stats3
    P: "XF:23ID1-ES{AXIS}"
    R: "Stats3:"
    NDARRAY_PORT: ROI3
    XSIZE: 1024
    YSIZE: 1024
    HIST_SIZE: 20

  - type: ADCore.NDStats
    PORT: Stats4
    P: "XF:23ID1-ES{AXIS}"
    R: "Stats4:"
    NDARRAY_PORT: ROI4
    XSIZE: 1024
    YSIZE: 1024
    HIST_SIZE: 20

  - type: ADCore.NDStats
    PORT: Stats5
    P: "XF:23ID1-ES{AXIS}"
    R: "Stats5:"
    NDARRAY_PORT: AXIS1
    XSIZE: 1024
    YSIZE: 1024
    HIST_SIZE: 20

  - type: ADCore.NDFileHDF5
    PORT: HDF1
    P: "XF:23ID1-ES{AXIS}"
    R: "HDF1:"
    NDARRAY_PORT: AXIS1

  - type: ADCore.NDFileTIFF
    PORT: TIFF1
    P: "XF:23ID1-ES{AXIS}"
    R: "TIFF1:"
    NDARRAY_PORT: AXIS1

  - type: ADCore.NDCircularBuff
    PORT: CB1
    P: "XF:23ID1-ES{AXIS}"
    R: "CB1:"
    NDARRAY_PORT: AXIS1
