axis_standard.hdf5.reg_root = "/tmp/hdf5"
axis_standard.hdf5.write_path_template = "/tmp/hdf5/%Y/%m/%d"
axis_standard.hdf5.read_path_template = "/tmp/hdf5/%Y/%m/%d"
axis_standard.hdf5.path_semantics = "posix"
axis_standard.hdf5.file_path.path_semantics = "posix"
axis_cont.hdf5.reg_root = "/tmp/hdf5"
axis_cont.hdf5.write_path_template = "/tmp/hdf5/%Y/%m/%d"
axis_cont.hdf5.read_path_template = "/tmp/hdf5/%Y/%m/%d"
axis_cont.hdf5.path_semantics = "posix"
axis_cont.hdf5.file_path.path_semantics = "posix"

